# Generated by Django 4.1.3 on 2022-12-07 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
