# Generated by Django 4.1.3 on 2022-12-10 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0006_movieorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="bought_by",
            field=models.ManyToManyField(
                related_name="buyed_movies",
                through="movies.MovieOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
