# Generated by Django 4.1.3 on 2022-12-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_rename_added_by_movie_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="added_by",
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
    ]
