# Generated by Django 4.1.3 on 2022-12-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='movieorder',
            options={'verbose_name': 'Filme Comprado', 'verbose_name_plural': 'Filmes Comprados'},
        ),
    ]
